# Generated by Django 4.2.5 on 2023-09-27 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_items', models.IntegerField()),
                ('transaction_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cashier.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cashier.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cashier.user'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='item',
            field=models.ManyToManyField(through='Cashier.Transaction_items', to='Cashier.product'),
        ),
    ]
