# Generated by Django 4.2.5 on 2023-09-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cashier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction_items',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
